### ISSUE TITLE
  Implement Better HiDPI Support

### ISSUE THREAD

**Issue by Foggalong** [numixproject/circle-core#2377]
The brilliant folks at elementary recently went to a summit to talk to the GNOME folks. They talked about various things including increased collaboration (yay!) but the thing important for Numix is that they discussed how to implement better HiDPI support in their icon themes. This is the [relevant commit](https://code.launchpad.net/~elementary-design/elementaryicons/hidpi-test/+merge/263317) on Launchpad for the elementary icon theme and we basically need to dig through this and find what we need to add to our themes. 

I'd really like to finish #190 first since adding support for both involves significant changes to the `index.theme` file. The equivalent issue for Base is [found here](https://github.com/numixproject/numix-icon-theme/issues/610).

**Comment by Foggalong** [comment]
Started working on this in the [HiDPI branch](https://github.com/numixproject/numix-icon-theme-circle/tree/hidpi)

**Comment by palob** [comment]
Reading the elementary blog entry I wonder if the presented solution is actually applicable to Numix Circle with only one scalable size.
As far as I understand the blog refers to icon themes with differently designed icons for different sizes (as is the case with Numix base for some icons) and proposes not to use the next bigger (differently designed) sized icons but to scale up say the 64x by a factor 2 for 2x HiDPI scaling.

**Comment by Foggalong** [comment]
It doesn't apply so much to Circle (as you say it uses 1 size fits all) but it's more needed in Base, so I figure it would be easier for changes down the line if it's just implemented identically in both

**Comment by Foggalong** [comment]
This has now been fixed in [this commit](https://github.com/numixproject/numix-icon-theme-circle/commit/0cd7d688b13ec1284c37e19bcf419b1b59ad6709), and rudimentary HiDPI support is now in the repos. All that's left to do now is fix #2545 (no small task).
