### ISSUE TITLE
weird icons on large screen

### ISSUE THREAD

**Issue by keunes** [numixproject/circle-core#2475]
When I plug in my laptop to a monitor with 1920x1080 pixels, everything on ubuntu looks smooth, except for most of the Numix icons in the launcher. See image below. The window-switcher (using alt+tab) does have good looking massive icons. Or maybe then it's something in Unity (haven't tried with the regular icon-set)?

![screenshot from 2015-08-12 18 06 39](https://cloud.githubusercontent.com/assets/11229646/9229458/7f730108-411d-11e5-9c65-02aea6249a01.png)

**Comment by PaoloRotolo** [comment]
I'm using an 1920x1080 monitor and Numix Circle works well...

**Comment by keunes** [comment]
Hmm. Maybe it's a bug in unity/compiz/whatsoever, then? I don't know how this all works...

In any case I've reported a bug in Launchpad: https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1484259

**Comment by wa4557** [comment]
Yeah I guess this is a known bug. Iirc you have to set the size of your dash icons to an even number instead of an odd number

**Comment by keunes** [comment]
Thanks. I only can set even numbers in the normal settings pane, but apparently there are also a few sizes that don't render weird icons.
Added the info to the bug report on Launchpad.
Guess I'll set a different size for now...

(I found another bug, but will make a new one. Guess we can close this one.)

**Comment by wa4557** [comment]
yeah that was just from memory :) There is somewhere a bug report on launchpad that addresses this issue; couldn't find it. Anyways that's obviously not a numix issue

**Comment by Foggalong** [comment]
I'll mark this as bug and keep it open until the Unity devs respond :)

**Comment by wa4557** [comment]
There seems to be a fix released that will land in Unity 7.3.3 https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1446081

**Comment by Foggalong** [comment]
Excellent \O/ just need 7.3.3 to land in the repos now

**Comment by Foggalong** [comment]
7.3.3 has now landed an it's all fine and dandy in the latest releases :+1:
