### ISSUE TITLE
Does a HIDPI implementation make sense here?

### ISSUE THREAD

**Issue by wa4557** [numixproject/circle-core#2603]
1. First off: I guess we need to add a proper HIDPI implementation here in circle as well at least for the `panel` folders, but:
2. I'm unsure if the `48@2x` approach is necessary for the apps folders as well, because there is only one size after all. What do you guys think?
3. I guess we should at least make the naming (`48x48` -> `48`) consistent
4. Is the `scalable` folder really necessary, couldn't this be easier made with a `MinSize` and `MaxSize` for the `48` sized folder? (Doesn't matter that much actually)

**Comment by bil-elmoussaoui** [comment]
1 - Should be implemented for the panel folders i guess! 
2 - Maybe once this got fixed #2546 
3 - :+1: 
4 - Totally agree with you!

**Comment by dirtydancing** [comment]
As to 4.: Currently, the `scalable/apps` folder (folder symlink with the target `48x48/apps`) is needed for GNOME Shell. The icons only from `48x48/apps` will be displayed blurry in the icon overview.

There might also be other reasons for the `scalable/apps` folder (?).

**Comment by Foggalong** [comment]
Basically, yes. We're gonna implement full HiDPI here too regardless of whether it's fixed before or after #2545. And yeah, the `scalable` folder is specifically needed for GNOME.

**Comment by wa4557** [comment]
Ok so HIDPI for all folders that are currently here. I get that GNOME desktop needs scalable app icons, but for this it is not necessary to have a seperate scalable apps folder, the same thing can be done by adding `MinSize=8` `MaxSize=512` to the `48/apps` folder. Just saying...

**Comment by wa4557** [comment]
@dirtydancing You are using a gnome shell aren't you. Fancy to test if this branch works for you?
https://github.com/wa4557/numix-icon-theme-circle/tree/hidpi

**Comment by dirtydancing** [comment]
@wa4557 I checked: Confirmed that with ARCH/GNOME (3.18), your branch works, no blurry icons :+1: 

I do not have HiDPI, though, so I cannot really say anything relating to that part.

**Comment by wa4557** [comment]
Cool, yeah the HIDPI part is fine on my machine (hidpi) so this should be OK :)

**Comment by wa4557** [comment]
Since the new system is now in place, wouldn't it be a good time to add @2x folders now? Not sure where in the script those icons are generated

**Comment by Foggalong** [comment]
At the moment folders which don't contain icons are just added manually to the packaging repository. That might change in future, but it'll do for now :)

**Comment by wa4557** [comment]
So a commit in the "original" repository is necessary? (Since now the folders are correctly named `48` instead of `48x48` adding them makes sense)

**Comment by Foggalong** [comment]
Yeah, [in this one](https://github.com/numixproject/numix-icon-theme-circle)
