### ISSUE TITLE
Icon for Trimage

### ISSUE THREAD

**Issue by Stunkymonkey** [numixproject/circle-core#2746]
**Original icon:**
![Image of Trimage](http://trimage.org/trimage-icon.png)

**Icon name:** trimage

**Notes:** It's a software for compressing images for the web without losing quality.

**Additional info:** also has a tray icon, but i am not sure how to get infos about the tray

**Comment by bil-elmoussaoui** [comment]
can you paste the output of `sudo find -name trimage-icon.png`?

**Comment by Stunkymonkey** [comment]
`[felix@felix-pc /]$ cd / && sudo find -name trimage-icon.png`
`[felix@felix-pc /]`
no output

**Comment by bil-elmoussaoui** [comment]
@Stunkymonkey Can you open the application and go to `/tmp` and see if there's any folder with a name like `sni-qt`?

**Comment by Stunkymonkey** [comment]
no folder or file starting with `sni`
only `qt` things are:
qipc_sharedmemory_qtsingleapplicationbfde75a5bf91e5179df8ee7ad4456d91fef8ca2ca6aa
qtsingleapplication-5230-3e8
qtsingleapplication-5230-3e8-lockfile

**Comment by bil-elmoussaoui** [comment]
Well, for the tray icon open an issue on Hardcode-Tray : https://github.com/bil-elmoussaoui/Hardcode-Tray  (the recommended hardcoded tray icons fixer by Numix). And i will see what i can do

**Comment by Stunkymonkey** [comment]
Also remeber adding the tray-icon, which is fixed:
https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/128

add `trimage-indicator`

**Comment by Stunkymonkey** [comment]
Has been added
#3089
