### ISSUE TITLE
Desktop icon incorect

### ISSUE THREAD

**Issue by Lev09** [numixproject/circle-core#3252]
Hello.
I really like your work guys and will be happy if you will make another icon for **desktop**
I don't know maybe the problem is my Linux distribution, but it shows  **Dock** icon for **desktop**

I am using Ubuntu 14.04

**Comment by bil-elmoussaoui** [comment]
Which dock are you talking about ? + can you share a screenshot ? :)

**Comment by Lev09** [comment]
![image](https://cloud.githubusercontent.com/assets/4953382/16310017/db003430-397b-11e6-8bae-c8a39b69290a.png)

**Comment by palob** [comment]
Please add the information asked for in the [readme](https://github.com/numixproject/numix-icon-theme-circle#icon-requests).

That aside, why would you need a dock icon within the dock?

**Comment by Lev09** [comment]
@palob  sorry but I don't understand what you are trying to tell !

Look here is the icon for "desktop" in Ubuntu's original theme:
![image](https://cloud.githubusercontent.com/assets/4953382/16333792/500742a4-3a0e-11e6-8ef5-d3441bdcb790.png)

And here is the icon for "desktop" from your icon pack: 
![image](https://cloud.githubusercontent.com/assets/4953382/16333842/88a7a5ea-3a0e-11e6-9eca-b51a59a6413c.png)
Icon from your icon-pack looks more like  "Dock" icon, but not icon of "Desktop"

**Comment by palob** [comment]
Alright, now I get it. I took you wanted to report something wrong with what is shown as the icon for Cairo dock :)

**Comment by palob** [comment]
How about this?
![cs-desktop](https://cloud.githubusercontent.com/assets/7050624/16435623/ba14d58a-3d97-11e6-9bf4-764f1a039bc4.png)

**Comment by Lev09** [comment]
This is what I wanted. How can I use it? Where is it?

**Comment by palob** [comment]
We can change the symlink. Do you know which icon it is exactly for Ubuntu? ``desktop.svg``?

You can use it by editing the ``.desktop`` file located in ``usr/share/applications`` (you'll find the name of the currently used icon as well).

You'll find more informtion in the  [readme](https://github.com/numixproject/numix-icon-theme-circle#icon-requests).
