### ISSUE TITLE
Request: Firefox

### ISSUE THREAD

**Issue by El-Zipo** [numixproject/circle-core#3254]
Please create a new beautiful firefox icon look like the firefox icon in Paper icons.
Because current firefox icon is not beautiful and I don't like it.
Please please please.

Thanks.

**Comment by nstommel** [comment]
Actually, I disagree; I think the Firefox icon is quite nice.

**Comment by Foggalong** [comment]
I've [made a poll](https://plus.google.com/+NumixProjectOrg/posts/M5buzhUA42E) to see what the general sentiment within the community is on this.

**Comment by Foggalong** [comment]
Yeah, majority of people love the icon and even those who don't don't hate it. We'll be keeping the current design
