### ISSUE TITLE
Icon for World of Tanks

### ISSUE THREAD

**Issue by codefuhrer** [numixproject/circle-core#3280]
It doesn't have an official linux version, but it can be launched via Wine without any problems (described on the [official website](http://worldoftanks.eu/en/content/soft/pc_programs/1311/)).

I made this icon for myself, can PR if it's OK .

![1](https://cloud.githubusercontent.com/assets/2178368/16661712/df24b142-447c-11e6-9abc-c3a46c4179d0.png)

Colors taken from their [Android app](https://play.google.com/store/apps/details?id=ru.worldoftanks.mobile).

**Comment by palob** [comment]
Please feel free open a PR, it's hard to do the review just based on the PNG preview.
