### ISSUE TITLE
Google Photos webapp icon missing

### ISSUE THREAD

**Issue by szekeres2016** [numixproject/circle-core#3339]
Hello, Google Photos Webapp: https://chrome.google.com/webstore/detail/google-photos/hcglmfcclpfgljeaiahehebeoaiicbko could use a symlink for the already existing icon file in the package: chrome-efjnaogkjbogokcnohkmnjdojkikgobo-Default.svg

**Comment by palob** [comment]
Hi, your link is broken. To get a working link on GitHub you just need to paste it. No whatsoever markup is needed.

**Comment by szekeres2016** [comment]
Fixed it! :)
