### ISSUE TITLE
Chrome Web Store icon missing

### ISSUE THREAD

**Issue by szekeres2016** [numixproject/circle-core#3347]
This is the last missing one on my system I promise! :) Unfortunately I cannot provide a link for the chrome webstor webapp since its its the store itself missing the icon. The application ID and icon ID is: **chrome-ahfgeienlihckogmohjhadlkjgocpleb-Default**

The original app icon looks like this:
![chrome internetes aruhaz](https://cloud.githubusercontent.com/assets/20751590/17319542/a0187e04-588e-11e6-88c3-83d77a443abb.png)

Based on your other software center icons something like this would look great I think:
![softwarecenter](https://cloud.githubusercontent.com/assets/20751590/17319563/bbf07078-588e-11e6-8e5e-59d89cfecb8b.png)

Thanks again for the great work you guys do!

**Comment by palob** [comment]
Got this
![chrome-ahfgeienlihckogmohjhadlkjgocpleb-default](https://cloud.githubusercontent.com/assets/7050624/17713463/55903c0a-63fb-11e6-80b6-6c7a0b93b2f1.png)

Are you sure about the name?

**Comment by szekeres2016** [comment]
Hi I'll paste the .desktop file content:

#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Chrome internetes áruház
Exec=/opt/google/chrome/google-chrome --profile-directory=Default --app-id=ahfgeienlihckogmohjhadlkjgocpleb
Icon=chrome-ahfgeienlihckogmohjhadlkjgocpleb-Default
StartupWMClass=crx_ahfgeienlihckogmohjhadlkjgocpleb

"Chrome internetes áruház" is localized for Chrome Web Store
