### ISSUE TITLE
Frozen Bubble Icon missing

### ISSUE THREAD

**Issue by szekeres2016** [numixproject/circle-core#3365]
Good day, Frozen Bubble, my favorite classic open source linux game could use a circle icon. The file name is "**frozen-bubble.desktop**" and the icon is:

Icon=frozen-bubble

Original icon looks... not that great:
![frozen-bubble](https://cloud.githubusercontent.com/assets/20751590/17490845/2d38f802-5da5-11e6-8d1d-99f93e7871c7.png)

**Comment by palob** [comment]
Here's a draft

![frozen-bubble](https://cloud.githubusercontent.com/assets/7050624/17536037/9cfe207a-5e92-11e6-836d-2dda7f4c39d1.png)

**Comment by szekeres2016** [comment]
I think there is no need to remove the arrow, it's more recognizable this way, nice icon! :)

**Comment by palob** [comment]
What do you think @Foggalong ?

**Comment by Foggalong** [comment]
It *should* be okay. Set up a pull request and I'll give it a check over :)
