### ISSUE TITLE
Icon for Visual Studio Code, and VS Code Insiders

### ISSUE THREAD

**Issue by pete-otaqui** [numixproject/circle-core#3370]
Hi,

this editor, in both it's forms is cross-platform, and would be great to have nice icons for.

It may not be straightforward since the icon name in the *.desktop file that is created is just "code"

**Comment by Foggalong** [comment]
As discussed elsewhere we can't fix this icon because the name is too generic. Please ask the developers to choose a better name like `vscode`

**Comment by pete-otaqui** [comment]
Done:

https://github.com/Microsoft/vscode/issues/10523

**Comment by Foggalong** [comment]
Basically a wontfix on their end then :/

**Comment by magnusart** [comment]
Arch Linux has Visual Studio Code repackaged with the icon name `visual-studio-code`. Are there any icons ready made for numix frost theme that I can install manually? The new vscode icon from microsoft is very ugly.

**Comment by Foggalong** [comment]
@magnusart That icon [is in the theme](https://github.com/numixproject/numix-icon-theme-square/blob/master/Numix-Square/48/apps/visual-studio-code.svg) so whoever is maintaining your Arch packaging just hasn't updated it to the latest version

**Comment by bilelmoussaoui** [comment]
@magnusart Numix frost is not maintained anymore
@Foggalong I maintain the square theme on Archlinux and it's up to date 👍 i don't have any idea about the circle one
