### ISSUE TITLE
Icon for Redis Desktop Manager

### ISSUE THREAD

**Issue by fmargarido-daitan** [numixproject/circle-core#3410]
Icon for RDM is missing.

```
[Desktop Entry]
Version=1.0
Name=Redis Desktop Manager
Comment=Redis Desktop Manager
Type=Application
Categories=Development;
Exec=/usr/share/redis-desktop-manager/bin/rdm.sh
Terminal=false
StartupNotify=true
Icon=/usr/share/redis-desktop-manager/bin/rdm.png
```

![rdm](https://cloud.githubusercontent.com/assets/16599037/18350244/69e77292-75ab-11e6-9bf0-330d8b39dfef.png)

Thanks.

**Comment by palob** [comment]
[Already in](https://github.com/numixproject/circle-core/blob/master/icons/48/rdm.svg)

**Comment by fmargarido-daitan** [comment]
Great, thanks for the heads up!
