### ISSUE TITLE
Webstorm circle icon

### ISSUE THREAD

**Issue by DraganKovacevic** [numixproject/circle-core#3419]
Please add circle light icon for Webstorm.

Icon=webstorm.svg

![screenshot from 2016-09-11 13-45-41](https://cloud.githubusercontent.com/assets/7206237/18417045/124d347c-7826-11e6-8f7c-65ab0c759c81.png)

**Comment by Foggalong** [comment]
[We already have this!](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48/apps/webstorm.svg) See the readme section on hardcoded icons for more information.
