### ISSUE TITLE
PhpStorm Circle icon

### ISSUE THREAD

**Issue by DraganKovacevic** [numixproject/circle-core#3420]
Please add circle light icon for PhpStorm.

Icon=webide.png

![screenshot from 2016-09-11 13-47-04](https://cloud.githubusercontent.com/assets/7206237/18417059/410cf450-7826-11e6-82df-d2c8d4a3d2be.png)

**Comment by Foggalong** [comment]
[We already have this!](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48/apps/webide.svg) See the readme section on hardcoded icons for more information.
