### ISSUE TITLE
Slack circle icon

### ISSUE THREAD

**Issue by DraganKovacevic** [numixproject/circle-core#3421]
Please add circle light icon for Slack.

Icon=/usr/share/pixmaps/slack.png

![screenshot from 2016-09-11 13-48-47](https://cloud.githubusercontent.com/assets/7206237/18417069/7f09ed80-7826-11e6-8984-78b0c51d2bb9.png)

**Comment by Foggalong** [comment]
[We already have this!](https://github.com/numixproject/numix-icon-theme-circle/blob/master/Numix-Circle/48/apps/slack.svg) See the readme section on hardcoded icons for more information.
