### ISSUE TITLE
Icons taking more space than they should

### ISSUE THREAD

**Issue by hochopepa-codes** [numixproject/circle-core#3435]
This is default **elementary OS** (Loki) theme.

![selection_003](https://cloud.githubusercontent.com/assets/8946984/19009136/079cf2d8-8771-11e6-90d6-eb7ee23ed844.png)

And this is **Numix-Circle**

![selection_002](https://cloud.githubusercontent.com/assets/8946984/19009077/9605224e-8770-11e6-93bb-f9ecb1ebd3e9.png)

You can clearly see that some icons (like notification center, session manager and audio manager...) are taking way more space than others (like deluge and battery). 

Is there any _fix_ to this?

**Comment by Foggalong** [comment]
This is an issue with the [base theme](https://github.com/numixproject/numix-icon-theme). This repo is just for app icons :)

**Comment by hochopepa-codes** [comment]
Sorry for posting in a wrong repo.
